version: '2'

services:
    mongodb:
        image: mongo
        restart: always
        volumes:
            - /data/db
    savegame_service:
        image: ttommeke/idp_savegame_service
        restart: always
        environment:
            - MONGODB_DATABASE=mydatabase
            - PORT=80
        depends_on:
            - mongodb
        links:
            - mongodb:mongodb
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=TheseHaveToBeTheSame
            - POSTGRES_USER=docker
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
    account_service:
        image: ttommeke/idp_account_service
        restart: always
        environment:
            - POSTGRES_PASSWORD=TheseHaveToBeTheSame
            - POSTGRES_USER=docker
            - PORT=80
        depends_on:
            - db
        links:
            - db:db
    question_service:
        image: ttommeke/idp_question_service
        restart: always
        environment:
            - JWTSecret=TomGeefInsEenSecret!
            - POSTGRES_PASSWORD=TheseHaveToBeTheSame
            - POSTGRES_USER=docker
            - PORT=80
        depends_on:
            - db
        links:
            - db:db
    proxy_service:
        image: ttommeke/idp_proxy
        restart: always
        environment:
            - PORT=80
        ports:
            - "80:80"
        links:
            - account_service:account_service
            - question_service:question_service
            - savegame_service:savegame_service
